language: csharp
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - uuid-dev
    - curl
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade 1.0.0-rc1-update2 -r coreclr
  - dnu restore
script:
  - dnx /home/travis/build/ollejacobsen/corebrowser/tests/CoreBrowser.Tests test