version: 1.0.{build}
image: Visual Studio 2017
cache: C:\Users\appveyor\.nuget\
before_build:
- cmd: dotnet restore
build_script:
- ps: dotnet build c:\projects\corebrowser\CoreBrowser.sln
test_script:
- ps: dotnet test c:\projects\corebrowser\tests\CoreBrowser.Tests\CoreBrowser.Tests.csproj